- name: Deploy Dockerized Node App Locally
  hosts: web
  connection: local
  tasks:
    - name: Pull Docker image
      shell: docker pull akshayjarad/myapp:latest

    - name: Stop and remove old container
      shell: |
        docker stop myapp || true
        docker rm myapp || true

    - name: Run container
      shell: docker run -d --name myapp -p 80:3000 akshayjarad/myapp:latest
